name: Deploy Django to Azure VM

on:
  push:
    branches:
      - master  # Change to your branch if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AZURE_VM_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.AZURE_VM_IP }} >> ~/.ssh/known_hosts

      - name: Deploy to Azure VM
        run: |
          ssh ${{ secrets.AZURE_VM_USER }}@${{ secrets.AZURE_VM_IP }} << 'EOF'
            #git clone https://github.com/kumar4world/Django.git
            cd /home/${{ secrets.AZURE_VM_USER }}/Django  # Change to your project path
            python3 -m venv venv
            pip install --upgrade pip
            pip install -r requirements.txt
            #git pull origin main  # Pull latest changes
            source venv/bin/activate  # Activate virtual environment
            pip install -r requirements.txt  # Install dependencies
            python TravelPlanner/manage.py migrate  # Apply database migrations
          EOF

